version: '3.7'
services:
    mongodb_container:
      image: mongo:latest
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: admin
      ports:
        - 27017:27017
      volumes:
        - mongodb_data_container:/data/db
    nestjs_api:
      image: domco545/golden-hammer-backend
      environment:
        MONGO_CONNECTION_STRING: mongodb://root:admin@mongodb_container:27017/golden-hammer?authSource=admin
        PORT: 3000
      command: npm run start:prod
      ports:
        - 4003:3000
networks:
  default:
    external: true
    name: golden

volumes:
  mongodb_data_container: